### ISSUE TITLE
https://orval.dev/

### ISSUE THREAD

**Issue by jozef-slezak** [rametta/rapini#28]
This project seems to be simlar to https://orval.dev/. Do you want to join forces?

**Comment by rametta** [comment]
@jozef-slezak I'm not against it. How do you propose we join forces?

**Comment by jozef-slezak** [comment]
First of allI would suggest to compare feature list of orval.dev and rapini.

**Comment by rametta** [comment]
What to do after that? I think we would need a full plan

**Comment by jozef-slezak** [comment]
Do you have any roadmap for rapini? It seems that rapini and orval.dev has common feature set. Does it makes sense to you to contribute to orval.dev since it hase 1k commits and 1k starts, and https://orval.dev/playground ?

**Comment by rametta** [comment]
There is no roadmap, rapini is pretty much feature complete, it will just be updated periodically to support new versions of React Query, SWR, and/or OpenAPI.
Is your suggestion that you want rapini to port over missing functionality to orval and then shut down rapini? I'm not sure that would be beneficial since both have different API's

**Comment by refo** [comment]
Sorry for barging into your conversation but, rapini doesn't seem cover the situations where you need a POST request to be query instead of mutation.

**Comment by la55u** [comment]
My take on this: rapini has (from the look of it) a very solid core that is a more viable approach to generating clients than Orval's solution. Maybe it could be ported over to be used as a base for Orval somehow and support it's wide range of feature set and configuration options?

**Comment by jozef-slezak** [comment]
What approach would be suitable from your perspective?

**Comment by rametta** [comment]
@jozef-slezak I don't really have any approach. I honestly don't mind keeping these libraries separate - I don't see a big benefit or value to merging them. Since they have different API's I think it's nice that users get a choice between 2 great tools to use based on which API they like more.

I was open to hearing any ideas to collaborating but it seems like there is no plan. I will close this issue now but if anyone comes up with a plan for the future to collaborate then feel free to reopen this issue. Thank you
