### ISSUE TITLE
Evaluation report (with Vue 3 + Vue Query)

### ISSUE THREAD

**Issue by Maxim-Mazurok** [rametta/rapini#40]
I've tried to use this library for my Vue 3 app.
With minor tweaks, it's possible to use (change a few imports and that's it).
However it has all the same reactivity issues out of the box as the ones mentioned in https://github.com/anymaniax/orval/pull/852

Kind of an advantage over ovral that I've noticed is that rapini does `.then((res) => res.data),` for axios requests, so you don't have to type `.data` every time. Same can be disadvantageous as it limits rare use-cases when you might need response headers.

On the topic of headers, we have "X-Api-Key" header required for each request, but rapini doesn't seem to pass it, yet requires it to be passed which is a bit annoyuing. Orval seems to ignore it altogether so I set it in the global axios interceptors.

Also, on the topic of the same header - it was producing invalid TS, failing to transform `X-Api-Key` into a valid argument name like `XApiKey`.

Other disadvantages would be less customization and not as complete of a solution IMO at first glance.

I hope this helps maintainers to improve and helps users in their research, cheers!

**Comment by rametta** [comment]
Hi @Maxim-Mazurok, thank you for the valuable feedback.

Regarding headers, my solution is to set global default on the axios instance - that was a design decision but I think it's the right call because you wouldn't want to set the same header every time manually. Example:

```js
myAxiosInstance.defaults.headers.common['Authorization'] = 'AUTH_TOKEN';
```

For the "invalid TS" issue you are facing, would you be able to paste your OpenAPI file here, just the part that would be causing the issues? I would love to investigate further and push out a fix.

> Other disadvantages would be less customization and not as complete of a solution IMO at first glance.

Would you be able to clarify what is meant by less customizable? Rapini provides a lot of customization options at build-time and runtime, but it may not be obvious, perhaps some more documentation can be written to help clarify any unknown customization.

If you have any other feedback around providing a more "complete solution", please let me know, cheers!

**Comment by Maxim-Mazurok** [comment]
Kinda makes sense about headers. I think in axios-typescript generator from openapi I could pass it as a config to client constructor, not sure.

I don't have code with me anymore but it was something like this: `function bla(X-Api-Key: string) => fetch(X-Api-Key)`. As you can see argument name is invalid and then it thinks that I want to subtract Api from X, etc.

Regarding customizations it's just a feel, I haven't used much of them yet. The same goes for "complete solution", it was just a feel that I got from initial interactions. Maybe I just wanted to convince myself to use orval because I already invested into fixing its reactivity or Vue... Either way, hope you didn't mind me sharing this, cheers!
