### ISSUE TITLE
Can rapini generate code with responseType: 'blob' for file GET requests?

### ISSUE THREAD

**Issue by mgunnerud** [rametta/rapini#43]
Hello,
This is a bit similar to issue #31, but I am trying to generate request code for a GET request which returns a PDF file, based on the following OpenAPI 3.0.1 path:

```
"/api/v1/publisering/vedtakelsesnotat": {
	"get": {
		"tags": [
			"Publisering"
		],
		"summary": "Hent vedtakelsesnotat",
		"operationId": "getVedtakelsesnotat",
		"responses": {
			"200": {
				"description": "OK",
				"content": {
					"application/pdf": {
						"schema": {
							"$ref": "#/components/schemas/StreamingResponseBody"
						}
					}
				}
			}
		},
		"security": [
			{
				"bearerAuth": []
			}
		]
	}
},
```

This generates the following code:
```
getVedtakelsesnotat: () =>
	axios
		.request<StreamingResponseBody>({
			method: 'get',
			url: `/api/v1/publisering/vedtakelsesnotat`
		})
		.then((res) => res.data),
```

However, since this returns a PDF file I would think the generated code should include responseType: 'blob', producing this code instead:
```
getVedtakelsesnotat: () =>
    axios
        .request<StreamingResponseBody>({
			method: 'get',
			url: `/api/v1/publisering/vedtakelsesnotat`,
			responseType: 'blob'
        })
        .then((res) => res.data),
```

Or is there a way to add responseType: 'blob' manually when calling this generated request?

**Comment by rametta** [comment]
Hello. Just giving a quick glance - I think there is some confusion because you wouldn't set the responseType inside the request object from the client - the server decides the resposne type. It is important we distinguish the difference between setting the content-type for a request, and setting the response type. For the example provided, setting the response type to blob wouldn't make a difference afaik since the server is already deciding to response with a pdf content type. Hope this helps
