### ISSUE TITLE
[Bug] OpenAPI Document version not supported

### ISSUE THREAD

**Issue by 1saifj** [rametta/rapini#54]
### Describe the bug

The OpenAPI document provided in Swagger v2 format is not supported by the `rapini` command when attempting to generate a React Query v5 package. The command fails with an error stating that the OpenAPI document version is not supported.

### To reproduce

1. Place the `swagger.json` file with the content below in your project directory.
2. Run the following command:
   ```bash
   npx rapini react-query v5 -p swagger.json
3. Observe the output:
```bash
Generating React Query v5 package using OpenAPI file swagger.json
API name: Swagger Petstore, Version: 1.0.7
Failed to parse API document. OpenAPI Document version not supported
```

Expected behavior
The rapini command should support Swagger v2 (OpenAPI 2.0) documents and successfully generate the React Query v5 package.

Swagger v2 File:
[swagger.json](https://github.com/user-attachments/files/16802784/swagger.json)

**Comment by rametta** [comment]
Hi @1saifj , thanks for opening the issue. We currently only support v3+ as seen here: https://github.com/rametta/rapini/blob/2378a4bbaa435ae85a6af3dd1b521f6b55d47729/src/react-query/generator.ts#L22-L26 

But PR's are always appreciated if you would like to add support for v2 - otherwise it is not planned to be added anytime soon
